# Generated by Django 3.0.4 on 2020-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajos',
            name='fecha_servicio',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='fecha_servicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
