# Generated by Django 3.0.4 on 2020-08-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='canceled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='canceled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
