# Generated by Django 3.0.4 on 2020-08-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200810_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='canceled',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='historicalclientes',
            old_name='canceled',
            new_name='estado',
        ),
    ]
