# Generated by Django 3.0.4 on 2020-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20200813_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='hora_servicio',
            field=models.TimeField(null=True, verbose_name='Hora del servicio'),
        ),
        migrations.AddField(
            model_name='historicalagenda',
            name='hora_servicio',
            field=models.TimeField(null=True, verbose_name='Hora del servicio'),
        ),
    ]
